version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "04:30"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: com.fasterxml.jackson.core:jackson-*
    versions:
    - ">= 0"
  - dependency-name: ch.qos.logback:logback-*
    versions:
    - ">= 0"
