version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "04:30"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  groups:
    jackson:
      patterns:
        - "com.fasterxml.jackson.core:jackson-*"
    junit:
      patterns:
        - "org.junit*"
    logback:
      patterns:
        - "ch.qos.logback:logback-*"
