/*
 * Copyright 2016 Daniel Nilsson
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.github.dannil.scbjavaclient.constants;

import java.util.Locale;

/**
 * <p>Constants which hold values for using the API.</p>
 *
 * @since 0.0.4
 */
public final class APIConstants {

    /**
     * <p>The default locale of the API (sv, SE).</p>
     **/
    public static final Locale FALLBACK_LOCALE = new Locale("sv", "SE");

    /**
     * <p>The default root URL of the API. Is generated by taking the URL to the API and
     * replacing the language segment with {@link #FALLBACK_LOCALE} language</p>
     */
    public static final String ROOT_URL = "https://api.scb.se/OV0104/v1/doris/" + FALLBACK_LOCALE.getLanguage()
            + "/ssd/";

    /**
     * <p>Constant for age code.</p>
     */
    public static final String AGE_CODE = "Alder";

    /**
     * <p>Constant for contents code.</p>
     */
    public static final String CONTENTSCODE_CODE = "ContentsCode";

    /**
     * <p>Constant for region code.</p>
     */
    public static final String REGION_CODE = "Region";

    /**
     * <p>Constant for sector code.</p>
     */
    public static final String SECTOR_CODE = "Sektor";

    /**
     * <p>Constant for time code.</p>
     */
    public static final String TIME_CODE = "Tid";

    /**
     * <p>Private constructor to prevent instantiation.</p>
     */
    private APIConstants() {

    }

}
