/*
 * Copyright 2016 Daniel Nilsson
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.github.dannil.scbjavaclient.constants;

import java.util.Locale;

/**
 * Constants which hold values for using the API.
 *
 * @since 0.0.4
 */
public final class APIConstants {

    /**
     * The default locale of the API (sv, SE).
     **/
    public static final Locale FALLBACK_LOCALE = new Locale("sv", "SE");

    /**
     * The default root URL of the API. Is generated by taking the URL to the API and
     * replacing the language segment with {@link #FALLBACK_LOCALE} language
     */
    public static final String ROOT_URL = "https://api.scb.se/OV0104/v1/doris/" + FALLBACK_LOCALE.getLanguage()
            + "/ssd/";

    /**
     * Constant for age code.
     */
    public static final String AGE_CODE = "Alder";

    /**
     * Constant for air pollutant code.
     */
    public static final String AIRPOLLUTANT_CODE = "Luftfororening";

    /**
     * Constant for contents code.
     */
    public static final String CONTENTSCODE_CODE = "ContentsCode";

    /**
     * Constant for economic indicator code.
     */
    public static final String ECONOMICINDICATOR_CODE = "EkoIndikator";

    /**
     * Constant for greenhouse gas code.
     */
    public static final String GREENHOUSEGAS_CODE = "Vaxthusgaser";

    /**
     * Constant for item code.
     */
    public static final String ITEM_CODE = "Kontopost";

    /**
     * Constant for market code.
     */
    public static final String MARKET_CODE = "Marknad";

    /**
     * Constant for region code.
     */
    public static final String REGION_CODE = "Region";

    /**
     * Constant for sector code.
     */
    public static final String SECTOR_CODE = "Sektor";

    /**
     * Constant for size class code.
     */
    public static final String SIZECLASS_CODE = "Storleksklass";

    /**
     * Constant for SNI 2002 code.
     */
    public static final String SNI2002_CODE = "SNI2002";

    /**
     * Constant for SNI 2007 code.
     */
    public static final String SNI2007_CODE = "SNI2007";

    /**
     * Constant for SNI 92 code.
     */
    public static final String SNI92_CODE = "SNI92";

    /**
     * Constant for SPIN 2002 code.
     */
    public static final String SPIN_2002 = "SPIN2002";

    /**
     * Constant for SPIN 2007 code.
     */
    public static final String SPIN_2007 = "SPIN2007";

    /**
     * Constant for SPIN 2015 code.
     */
    public static final String SPIN_2015 = "SPIN2015";

    /**
     * Constant for sub-sector code.
     */
    public static final String SUBSECTOR_CODE = "Delsektor";

    /**
     * Constant for sex code.
     */
    public static final String SEX_CODE = "Kon";

    /**
     * Constant for time code.
     */
    public static final String TIME_CODE = "Tid";

    /**
     * Constant for type of building code.
     */
    public static final String TYPEOFBUILDING_CODE = "Hustyp";

    /**
     * Constant for type of expenditure code.
     */
    public static final String TYPEOFEXPENDITURE_CODE = "Kostnadsslag";

    /**
     * Constant for type of value code.
     */
    public static final String TYPEOFVALUE_CODE = "VarTyp";

    /**
     * Private constructor to prevent instantiation.
     */
    private APIConstants() {

    }

}
