version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    ignored_updates:
      - match:
          # Should be upgraded all at once in a single PR; not yet possible 
          # with Dependabot so let's handle that manually
          dependency_name: "org.junit*"
      - match:
          # Should be upgraded all at once in a single PR; not yet possible 
          # with Dependabot so let's handle that manually
          dependency_name: "com.fasterxml.jackson.core:jackson-*"
