name: GitHub Actions CI

on:
  push:
    branches-ignore:
    - 'gh-pages'
    - '*tag*'
    - 'test/run-all-tests'
  schedule:
    - cron: '30 04 * * *'

jobs:
  build:
    strategy:
      matrix:
        java: [11, 12, 13]
      fail-fast: false
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-16.04
    steps:
      # If we get the same IP on concurrent builds and this triggers an error
      # on the API (rate limiting), this can be easily debugged by checking the log
    - name: Get IP
      run: 'echo IP: $(dig +short myip.opendns.com @resolver1.opendns.com)'
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn install -B -V -DtestsDayLimit=7
